-- Resolve actionable Supabase advisor findings after the schema reconciliation.

create index if not exists broker_order_events_user_idx
    on public.broker_order_events (user_id, occurred_at desc);

create index if not exists broker_order_intents_connection_idx
    on public.broker_order_intents (broker_connection_id)
    where broker_connection_id is not null;

create index if not exists broker_order_intents_discipline_idx
    on public.broker_order_intents (discipline_evaluation_id)
    where discipline_evaluation_id is not null;

-- 000 already creates the equivalent user_subscriptions_user_idx.
drop index if exists public.user_subscriptions_user_created_idx;

-- pattern_metadata is a legacy data table outside the core migration chain.
-- Add a stable row identity when the table exists and has no primary key.
do $$
begin
    if to_regclass('public.pattern_metadata') is not null
       and not exists (
           select 1
           from pg_constraint
           where conrelid = 'public.pattern_metadata'::regclass
             and contype = 'p'
       ) then
        alter table public.pattern_metadata
            add column if not exists id bigint generated by default as identity;
        alter table public.pattern_metadata
            add constraint pattern_metadata_pkey primary key (id);
    end if;
end;
$$;

